---

- name: Core Packages and Configurations
  hosts: all
  vars: 
#change the username and groupname to your username and groupname
    username: john
    groupname: doe

  tasks:
    - name: Install core packages
      become: true
      ansible.builtin.apt:
        name:
          - zsh
          - zfsutils-linux
          - git
          - fonts-font-awesome
          - btop
          - neofetch
          - neovim
          - fzf
          - vim
          - bash-completion
          - lsb-release
          - wget
          - curl
          - chrony
          - lvm2
        update_cache: true

    - name: Download spaceship using get_url
      get_url:
        url: https://starship.rs/install.sh
        dest: /home/"{{username}}"/install.sh
        group: "{{groupname}}"
        owner: "{{username}}"

    - name: Execute the starship install script 
      become: true
      command: sh /home/"{{username}}"/install.sh -f -y

    - name: Copy zsh config
      copy:
        src: ./config/.zshrc
        dest: /home/"{{username}}"/.zshrc

    - name: Create a Directory /home/"{{username}}"/nerdfonts
      file:
        path: /home/"{{username}}"/nerdfonts
        state: directory
        owner: "{{username}}"
        group: "{{groupname}}"

    - name: Clone a github repository nerfonts
      git:
        repo: https://github.com/ryanoasis/nerd-fonts
        dest: /home/"{{username}}"/nerdfonts
        depth: 1
        clone: yes
        update: yes

    - name: Install nerdfonts
      become: true
      command: bash /home/"{{username}}"/nerdfonts/install.sh -q

    - name: Copy Starship Conf
      copy:
        src: ./config/starship.toml
        dest: /home/"{{username}}"/.config/starship.toml

    - name: change user shell to zsh 
      become: yes
      user:
        name: "{{username}}"
        shell: /bin/zsh


    - name: Add sudo access for the user
      become: yes
      lineinfile:
        path: /etc/sudoers
        line: "{{username}}" ALL=(ALL:ALL) NOPASSWD:ALL"
        state: present
        validate: visudo -cf %s
