---
- hosts: '{{ host }}' 
  vars:
    username: jakob
    groupname: docker

  tasks:

    - name: Generate DB PW
      set_fact:
        db_password: "{{ lookup('community.general.random_string', length=32, min_lower=1, min_upper=1, min_numeric=1, special=false) }}"

    - name: Verify the generate password
      debug:
        var: db_password


    - name: Creates directory for Configs
      become: yes
      ansible.builtin.file:
        path: /etc/docker-ansible/unifi-wlc
        state: directory
        owner: "{{username}}"
        group: "{{groupname}}"
        mode: 0770
        recurse: yes

    - name: Create DB init Script
      copy:
        dest: /etc/docker-ansible/unifi-wlc/init-mongo.sh
        src: ./config/docker-unifi/init-mongo.sh
        owner: "{{username}}"
        group: "{{groupname}}"
        mode: 0775

    - name: Save DB password
      template:
        src: ./config/docker-unifi/db_password.j2
        dest: /etc/docker-ansible/unifi-wlc/db_password.txt
        owner: "{{username}}"
        group: "{{groupname}}"
        mode: 0660

    - name: create DB env
      template:
        src: ./config/docker-unifi/unifi-db.j2
        dest: /etc/docker-ansible/unifi-wlc/unifi-db.env
        owner: "{{username}}"
        group: "{{groupname}}"
        mode: 0660

    - name: create WLC env
      template:
        src: ./config/docker-unifi/unifi-network-application.j2
        dest: /etc/docker-ansible/unifi-wlc/unifi-network-application.env
        owner: "{{username}}"
        group: "{{groupname}}"
        mode: 0660
